spring:
  application:
    name: blog-in-action
  thymeleaf:
    encoding: UTF-8
    cache: false
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    connectionProperties: druid.stat.mergeSql=true
    maxActive: 200
    initialSize: 10
    maxWait: 60000
    minIdle: 10
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    favicon:
      enabled: false
  data:
    elasticsearch:
      cluster-nodes: 192.168.220.129:9300
      properties:
        transport:
          tcp:
            connect_timeout: 120s
      cluster-name: elasticsearch
      repositories:
        enabled: true
  redis:
    host: 20.18.10.129
    port: 6379
    password: 123456
    lettuce:
      pool:
        #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用redis.maxTotal
        maxActive: 600
        #最大空闲数
        maxIdle: 200
        minIdle: 0
        #控制一个pool可分配多少个jedis实例,用来替换上面的redis.maxActive,如果是jedis 2.4以后用该属性
        maxTotal: 1000
        #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        maxWaitMillis: 5000
server:
  port: 8080
  tomcat: 
      uri-encoding: UTF-8
  http:
      encoding: 
          force: true
          charset: UTF-8
          enabled: true
